{% set name = "bibtex-ruby" %}
{% set version = "5.1.4" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 5c5021b66e86c2d13d674100c9b2028063b16d262dd8dda4823daf2c6badfc03

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-latex-decode >=0.0,<1

test:
  commands:
    - ruby -r 'bibtex' -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: GPL-3.0
  license_family: GPL
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: BibTeX-Ruby is the Rubyist's swiss-army-knife for all things BibTeX

  description: |
    It includes a parser for all common BibTeX objects (@string, @preamble,
    @comment and regular entries) and a sophisticated name parser that tokenizes
    correctly formatted names; BibTeX-Ruby recognizes BibTeX string replacements,
    joins values containing multiple strings or variables, supports
    cross-references, and decodes common LaTeX formatting instructions to unicode;
    if you are in a hurry, it also allows for easy export/conversion to formats
    such as YAML, JSON, CSL, and XML (BibTeXML).
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/inukshuk/{{ name }}

extra:
  recipe-maintainers:
    - sodre
