travis:
  secure:
    BINSTAR_TOKEN: Wj0Kg7ldwB10RsKXKyPEDXyGUo45+DOmk8b+PeRRPIX9sMVRkRPScnaMLi/fPUHCK5ev2+it016ORfXWvzjL0NxI0Zn/gn9ccxVwlF+zMjhlIYQP9vyLE0zfP+wNGlYVQU6xpg2Qmo1HZJ/wo8MzrWcuWc3hWgvi/3rw7yMax6twlNT8uvpHGteVs+OvG4bGWfacG6R7z3GrNpdU0OWcYdB9IICtEzGiQtgGf+/DOhaaRMDaRt7NgOnv0v0lxMMmZmtmfzotjS4cfZIBdj7koxUHALpDfm1vNHQ2laqXcj7jGDdxg53dRfJqyo9qrbYnL8Li2q2FktTavpZA1BfOsDc17sK4nLmLnlIMmhlFftHdBXTqEvEhOdwB1/ACL+399vu3hJktmugZVJZ4EcrWDoCfMcWLT/XC7BWj5DeqhcGBnQFWljRHSGT6JKgSOLPXEQE7v/nZuiA9ggxij0wClXU8aDmUSvLOepsXp/kg20M5gI84MbG3Hp8JMm0yqpxiNNhoa+Cl63fKe7ay/rUdQ5dO8/yWy3FvoRqNRvHk5pLukw/HMnigRJTgziTHm0Hks5UsD7JajNUNBAJ6SNC0YKQcqX2OqWzFQAVGvVb/sDD5QcnLec4lqXUy1E1JiHNU2ZdOEuriZ4YVihKkqIaRH4Vznz2jIVJ0P/HOjiVtZ1A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
