travis:
  secure:
    BINSTAR_TOKEN: WLZGqDIjcM45ucKE27Bt18LAXCMtBhg/ibNKmdx0/B4ydJ26YNeK1mdjXI3lECKq1ZK2uxDIFq0o7UPXOHiRGgRp8xCUYjBAKZz9FgbBdsw8OsTf3vZ5dp7ta1d1fHPiws8SRbXhQyk2tbGOAS9DJ/vC8RUYhfGA3T9ROI6LBQWnLmK6LIflKlda3JeuqWj3Oyn1lXTlpN2xVLzxPg7j8fao7Jj1DumT3BH2PzlCI1sXc9vSWx1/Lz1wbd9yi3ERaTHBp3wuZqzvRjNEl8aZ+XgxLi7cN7gBsSSxN/ervxhnk7Qs3IN8nzjf0NMsRcnl3LzGPA0kY5LN0GFmG3e0JRaCb1C68S3SxzwSP9cY4VCUmL8fW6HQafxXdHAEOvZcSsmRwoMri6khYdKZ4kAqspQP0SjlWrU2UIdlVTCC7wjDt7ICLZaJfdlRgvzFHH1IshrdYOjq3a46B0v0ot2msido29JXV7KGMhZlihF5s3ujUZbSIOqFk6R4+b8eeaxThLudRr3gbp8cwv7QQPcoZMJnSgQtKuGDpx1W2NfS8ClGAMH8a+mArbdbBDxEjQbIBDZdvTZBbySU5UoWGk4UJT+wdLwNSibQwdj6OJ+cn3tWOGjlx3iI2Jgw4Zo4F+f0rTXYJ6Icxn14Oj+xsgAQ4smSuYZITOKYm14o0VeTEEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
